version: "3.8"

services:
  notes:
    build:
      context: .
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      - SERVER_PORT=3000
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - notes-mysql

  mysql:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nest-events
    volumes:
      - todo-mysql-data:/var/lib/mysql
    networks:
      - notes-mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  notes-mysql:
volumes:
  todo-mysql-data:




