apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP
  ports:
    - targetPort: 3306
      port: 3306

  selector:
    app: nestservice-mysql

  # kubectl create -f nestservice-service-3.yaml
