apiVersion: v1
kind: Pod
metadata:
  name: nestservice-mysql
  labels:
    app: nestservice-mysql
spec:
  containers:
    - name: nest-events-backend-mysql-1
      image: mysql:8.0.23
      env:
        - name: "MYSQL_USER"
          value: "nestservice"
        - name: "MYSQL_PASSWORD"
          value: "example"
        - name: "MYSQL_DATABASE"
          value: "nest-events"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "example":
      ports:
      - containerPort: 3306
