name: Node.js CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Install dependencies
        run: npm install

#      - name: Run test
#      - run: npm test


